### ISSUE TITLE
problem with gnubg android library

### ISSUE THREAD

**Issue by yousofkakhki** [alcacoop/it.alcacoop.backgammon#12]
hi there, i am sorry but i am new to android programming and cant find a way to place gnubg binaries to the lib folder l
https://github.com/alcacoop/it.alcacoop.backgammon/blob/master/android/libs/README
this is also asked here:
http://stackoverflow.com/questions/35678238/gnubg-lib-not-load-in-backgammon

> HERE

 YOU MUST COPY gnubg-android binaries

> 
but i dont now how to get them, or build them, 
please help me

**Comment by yousofkakhki** [comment]
solve it by doing ndk-build at the library folder and paste the binaries to the libs foldeer

**Comment by francov** [comment]
I'm glade to note that you solved the issue alone. Keep us updated on the progress of your fork, because we are happy to know that someone else is using gnubg.
