### ISSUE TITLE
Add support for analysis.

### ISSUE THREAD

**Issue by vext01** [alcacoop/it.alcacoop.backgammon#7]
How about support for analysis, like in the desktop version of GNUbg?

The "hint" option would also be useful for beginners.

**Comment by dom0** [comment]
At the moment online Analysis on mobile platform isn't in our timeline. It needs more work on native component (gnubg AI libs) and it requires huge computational resources on device (with related battery drain!).
Hint feature will be implemented in next releases, we are going to open new separated issue for this
Thank you for your feedback
